/** Stable feature names advertised in Gateway hello responses. */
export const GATEWAY_SERVER_CAPS = {
  BOARD_WIDGET_PUT_CANVAS_DOC: "board-widget-put-canvas-doc",
  CHAT_SEND_ROUTING_CONTRACT: "chat-send-routing-contract",
  CONTROL_UI_BROWSER_FOCUS: "control-ui-browser-focus",
  GATEWAY_RESTART_TARGET_SAFE: "gateway-restart-target-safe-v1",
  MODEL_CATALOG_SNAPSHOT: "model-catalog-snapshot",
  NODE_WORKER_BUNDLE_RETENTION: "node-worker-bundle-retention-v1",
  NODE_WORKER_BUNDLE_STATUS: "node-worker-bundle-status-v1",
  NODE_WORKER_CAPTURED_EXEC_POLICY: "node-worker-captured-exec-policy",
  NODE_WORKER_ENVIRONMENT_SESSION: "node-worker-environment-session-v1",
  NODE_WORKER_PORTAL_STREAM: "node-worker-portal-stream-v1",
  PUBLISHED_MODEL_CATALOG: "published-model-catalog",
  PROFILE_BINDING: "profile-binding-v1",
  PROGRESS_CARD_AGENT_SCOPE: "progress-card-agent-scope-v1",
  SESSION_SCOPED_CHAT_METADATA: "session-scoped-chat-metadata",
  SESSION_SCOPED_MODEL_CATALOG: "session-scoped-model-catalog",
  SESSION_UNREAD_ACK_CONTRACT: "session-unread-ack-contract",
  SESSION_GOAL_START: "session-goal-start-v1",
  SESSION_SETTINGS_CONTRACT: "session-settings-contract",
  SESSION_SETTINGS_CAS: "session-settings-cas-v1",
  SYSTEM_AGENT_WIZARD_CANCEL: "openclaw-chat-wizard-cancel",
  SYSTEM_AGENT_SETUP_MODEL_REF: "openclaw-setup-model-ref",
  TASK_SUGGESTIONS_ACCEPT_MODES: "taskSuggestions.acceptModes",
} as const;
